language: node_js

node_js:
  - '10'
#branches:
# only:
#    - dev
before_script:
  - psql -c 'create database grace_shopper;' -U postgres
#deploy:
# provider: heroku
# use heroku and travis clis to add encrypted api key
# app: some-app-name
# run:
#   - 'npm run seed'
# on:
#   branch: dev
